// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "../application"

import DropdownController from "./dropdown_controller"
application.register("dropdown", DropdownController)

import EmailValidationController from "./email_validation_controller"
application.register("email-validation", EmailValidationController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import LoginValidationController from "./login_validation_controller"
application.register("login-validation", LoginValidationController)

import MentionsController from "./mentions_controller"
application.register("mentions", MentionsController)

import PasswordValidationController from "./password_validation_controller"
application.register("password-validation", PasswordValidationController)

import SaveModalController from "./save_modal_controller"
application.register("save-modal", SaveModalController)

import UsernameValidationController from "./username_validation_controller"
application.register("username-validation", UsernameValidationController)

import TagPeopleController from "./tag_people_controller"
application.register("tag-people", TagPeopleController)

