detectors:
  IrresponsibleModule:
    enabled: false

  InstanceVariableAssumption:
    enabled: false

  FeatureEnvy:
    enabled: true

  TooManyStatements:
    max_statements: 8

  DuplicateMethodCall:
    enabled: true

  NilCheck:
    enabled: false

  ControlParameter:
    enabled: false

exclude_paths:
  - db/migrate
  - app/helpers
